
import '../models/catalog.dart';
import '../models/catalog_response.dart';
import '../models/menu.dart';
import '../models/merchant.dart';

/// Rich offline mock catalog used when no backend is configured, so the full
/// ordering loop + search demo works in development. Mirrors the §4 wire shapes.
class MockCatalog {
  MockCatalog._();

  static final CatalogResponse data = _build();

  static CatalogResponse _build() {
    final merchants = <Merchant>[
      const Merchant(
        id: 'sheger-kitchen',
        nameEn: 'Sheger Kitchen',
        nameAm: 'ሸገር ኩሽና',
        sefer: 'Bole Medhanealem',
        subCity: 'Bole',
        lat: 8.9888,
        lng: 38.7872,
        phoneGsm: '+251 911 224 410',
        prepMin: 28,
        rating: 4.7,
        tsomCertified: true,
        halalCertified: false,
        thermal: true,
        acceptsCash: true,
        acceptsChapa: true,
        isRestaurantOfTheDay: true,
        accent: '#C84B20',
        isOpen: true,
        cuisine: ['Ethiopian', 'Traditional'],
        features: ['vegan-friendly', 'raw-meat', 'qentre'],
        deliveryZones: ['Bole', 'Kirkos', 'Arada', 'Yeka'],
      ),
      const Merchant(
        id: 'habesha-coffee',
        nameEn: 'Habesha Coffee House',
        nameAm: 'ሀበሻ ቡና ቤት',
        sefer: 'Kazanchis',
        subCity: 'Kirkos',
        lat: 9.0105,
        lng: 38.7612,
        phoneGsm: '+251 555 882 120',
        prepMin: 6,
        rating: 4.4,
        tsomCertified: false,
        halalCertified: false,
        thermal: false,
        acceptsChapa: true,
        isOpen: true,
        accent: '#6E3A1F',
        cuisine: ['Coffee', 'Breakfast', 'Pastries'],
        features: ['vegan', 'gluten-free'],
        deliveryZones: ['Kirkos', 'Bole', 'Arada'],
      ),
      const Merchant(
        id: 'desta-kitfo',
        nameEn: 'Desta Kitfo & Siga',
        nameAm: 'ደስታ ክትፎ',
        sefer: 'Piazza',
        subCity: 'Arada',
        lat: 9.024,
        lng: 38.7469,
        phoneGsm: '+251 911 331 220',
        prepMin: 14,
        rating: 4.9,
        tsomCertified: false,
        halalCertified: false,
        thermal: true,
        acceptsCash: true,
        acceptsChapa: true,
        isOpen: true,
        accent: '#A93226',
        cuisine: ['Raw-meat', 'Ethiopian'],
        features: ['keto', 'high-protein', 'raw-meat'],
        deliveryZones: ['Arada', 'Bole'],
      ),
      const Merchant(
        id: 'vegan-bole',
        nameEn: 'Yetsom Delight',
        nameAm: 'የጾም ደስታ',
        sefer: 'Edna Mall',
        subCity: 'Bole',
        lat: 8.9935,
        lng: 38.7812,
        phoneGsm: '+251 911 778 330',
        prepMin: 20,
        rating: 4.6,
        tsomCertified: true,
        halalCertified: true,
        thermal: false,
        acceptsCash: true,
        acceptsChapa: true,
        isOpen: true,
        accent: '#1E6B3A',
        cuisine: ['Vegan', 'Plant-based'],
        features: ['vegan', 'plant-based', 'gluten-free', 'halal'],
        deliveryZones: ['Bole', 'Kirkos', 'Yeka'],
      ),
      const Merchant(
        id: 'pizza-mercato',
        nameEn: 'Mercato Pizza & Dough',
        nameAm: 'መርካቶ ፒዛ',
        sefer: 'Merkato',
        subCity: 'Arada',
        lat: 9.042,
        lng: 38.7512,
        phoneGsm: '+251 911 662 004',
        prepMin: 22,
        rating: 4.2,
        tsomCertified: false,
        halalCertified: true,
        thermal: false,
        acceptsCash: true,
        acceptsChapa: true,
        isOpen: false, // closed now — Open Now toggle hides it
        accent: '#C9B458',
        cuisine: ['Pizza', 'Italian'],
        features: ['halal', 'low-carb', 'keto-friendly'],
        deliveryZones: ['Arada'],
      ),
      const Merchant(
        id: 'keto-club',
        nameEn: 'The Keto Club',
        nameAm: 'ኬቶ ክለብ',
        sefer: 'CMC',
        subCity: 'Yeka',
        lat: 9.032,
        lng: 38.7882,
        phoneGsm: '+251 922 554 771',
        prepMin: 18,
        rating: 4.8,
        tsomCertified: false,
        halalCertified: true,
        thermal: false,
        acceptsCash: true,
        acceptsChapa: true,
        isOpen: true,
        accent: '#7A4B8B',
        cuisine: ['Keto', 'Healthy', 'Salads'],
        features: ['keto', 'low-carb', 'high-protein'],
        deliveryZones: ['Yeka', 'Bole'],
      ),
    ];

    const items = <MenuItem>[
      // Sheger Kitchen
      MenuItem(
        id: 'sk-doro-wot', merchantId: 'sheger-kitchen',
        nameAm: 'ዶሮ ወጥ', nameEn: 'Doro Wot', priceEtb: 420,
        category: 'Meat Wots', isTsom: false, isHalal: false, isRawMeat: false,
        hasInjeraStepper: true, spiceLevels: 3,
      ),
      MenuItem(
        id: 'sk-tibs', merchantId: 'sheger-kitchen',
        nameAm: 'ዘልዘል ጥብስ', nameEn: 'Zilzil Tibs', priceEtb: 380,
        category: 'Meat Wots', isTsom: false, isHalal: false, isRawMeat: false,
        hasInjeraStepper: true, spiceLevels: 3,
      ),
      MenuItem(
        id: 'sk-shiro', merchantId: 'sheger-kitchen',
        nameAm: 'ሽሮ ወጥ', nameEn: 'Shiro Wot', priceEtb: 245,
        category: 'Vegan / Yetsom', isTsom: true, isHalal: true, isRawMeat: false,
        hasInjeraStepper: true, spiceLevels: 2,
        dietaryTags: [DietaryTag.vegan, DietaryTag.tsom],
      ),
      // Habesha Coffee
      MenuItem(
        id: 'hc-buna', merchantId: 'habesha-coffee',
        nameAm: 'ቡና', nameEn: 'Habesha Buna', priceEtb: 85,
        category: 'Beverages', isTsom: true, isHalal: true,
      ),
      MenuItem(
        id: 'hc-genfo', merchantId: 'habesha-coffee',
        nameAm: 'ገንፎ', nameEn: 'Genfo with Berbere', priceEtb: 120,
        category: 'Breakfast', isTsom: true, isHalal: true,
        hasInjeraStepper: false, spiceLevels: 1,
      ),
      // Desta Kitfo
      MenuItem(
        id: 'dk-kitfo', merchantId: 'desta-kitfo',
        nameAm: 'ክትፎ', nameEn: 'Kitfo (raw or rare)', priceEtb: 460,
        category: 'Raw Meat', isTsom: false, isHalal: false, isRawMeat: true,
        hasInjeraStepper: true, spiceLevels: 3,
        dietaryTags: [DietaryTag.rawMeat, DietaryTag.highProtein],
      ),
      MenuItem(
        id: 'dk-tere', merchantId: 'desta-kitfo',
        nameAm: 'ጥሬ ስጋ', nameEn: 'Tere Siga', priceEtb: 520,
        category: 'Raw Meat', isTsom: false, isHalal: false, isRawMeat: true,
        hasInjeraStepper: true, spiceLevels: 2,
      ),
      // Yetsom Delight
      MenuItem(
        id: 'yd-beyainetu', merchantId: 'vegan-bole',
        nameAm: 'በየአይነቱ', nameEn: 'Beyainetu Veggie Platter', priceEtb: 300,
        category: 'Vegan / Yetsom', isTsom: true, isHalal: true,
        hasInjeraStepper: true, spiceLevels: 2,
        dietaryTags: [DietaryTag.vegan, DietaryTag.tsom, DietaryTag.glutenFree],
      ),
      MenuItem(
        id: 'yd-misir', merchantId: 'vegan-bole',
        nameAm: 'ምስር ወጥ', nameEn: 'Misir Wot', priceEtb: 230,
        category: 'Veggie Stews', isTsom: true, isHalal: true,
        hasInjeraStepper: true, spiceLevels: 2,
        dietaryTags: [DietaryTag.vegan, DietaryTag.tsom],
      ),
      // Keto Club
      MenuItem(
        id: 'kc-caesar', merchantId: 'keto-club',
        nameAm: 'ሳላት', nameEn: 'Keto Caesar Salad', priceEtb: 310,
        category: 'Salads', isTsom: false, isHalal: true,
        dietaryTags: [DietaryTag.keto, DietaryTag.lowCarb],
      ),
      MenuItem(
        id: 'kc-bowl', merchantId: 'keto-club',
        nameAm: 'ኦፕቲም', nameEn: 'High-Protein Bowl', priceEtb: 360,
        category: 'Healthy', isTsom: false, isHalal: true,
        dietaryTags: [DietaryTag.keto, DietaryTag.highProtein, DietaryTag.lowCarb],
      ),
    ];

    final config = AppConfig.fromJson(const {
      'serviceFee': 20,
      'deliveryFee2km': 80,
      'deliveryFee5km': 150,
      'deliveryFee8km': 240,
      'footFee': 45,
      'rainSurge': 40,
      'bunaRunFee': 50,
      'bunaMaxOrder': 150,
      'bunaMaxKm': 1,
      'courierSharePct': 80,
      'courierTipsPct': 100,
      'codFloatCap': 1500,
      'codSettlementHours': 24,
      'commissionPct': 12,
      'restaurantOfTheDayCommissionPct': 0,
      'ackTimeoutSeconds': 90,
      'smsProvider': 'afromessage',
      'smsCostEtb': 0.45,
      'rainMode': false,
      'fastingOverride': false,
      'vehicleCurfew': false,
      'restaurantOfTheDayId': 'sheger-kitchen',
      'inflationPct': 22,
      'feeMultiplier': 1.0,
      'demo': true,
    });

    return CatalogResponse(
      merchants: merchants,
      items: items,
      config: config,
      fasting: const FastingState(
        active: false,
        labelEn: '',
        labelAm: '',
        weekly: false,
      ),
      subCities: const [
        SubCity(id: 'bole', nameEn: 'Bole', nameAm: 'ቦሌ'),
        SubCity(id: 'kirkos', nameEn: 'Kirkos', nameAm: 'ኪርኮስ'),
        SubCity(id: 'yeka', nameEn: 'Yeka', nameAm: 'የካ'),
        SubCity(id: 'arada', nameEn: 'Arada', nameAm: 'አራዳ'),
      ],
    );
  }
}